### ISSUE TITLE
Bookmark conversion error on manjaro

### ISSUE THREAD

**Issue by sramauge** [ebruck/radiotray-ng#70]
With rt2rtng i've this error on bookmark conversion :

rt2rtng ~/.local/share/radiotray/bookmarks.xml > bookmarks.json
Traceback (most recent call last):
  File "/usr/bin/rt2rtng", line 81, in <module>
    root = etree.parse(sys.argv[1]).getroot()
  File "src/lxml/etree.pyx", line 3426, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "/home/stef/.local/share/radiotray/bookmarks.xml", line 440
lxml.etree.XMLSyntaxError: xmlParseEntityRef: no name, line 440, column 32

**Comment by ebruck** [comment]
Can you post your bookmarks.xml file?

**Comment by ebruck** [comment]
@sramauge This may be your problem:

>Problem: An XML parser returns the error “xmlParseEntityRef: noname”
>
>Cause: There is a stray ‘&’ (ampersand character) somewhere in the XML text eg. some text & some >more text
>
>Solution:
>
>Solution 1: Remove the ampersand.
>Solution 2: Encode the ampersand (that is replace the '&' character with '& amp;' ). Remember to >Decode when reading the XML text.
>Solution 3: Use CDATA sections (text inside a CDATA section will be ignored by the parser.) eg. <!>>[CDATA[some text & some more text]]>
>Note: ‘&’ ‘<' '>‘ will all give problems if not handled correctly.

https://stackoverflow.com/questions/7604436/xmlparseentityref-no-name-warnings-while-loading-xml-into-a-php-file
